accounts/templates/accounts/login.html
accounts/templates/accounts/signup.html
accounts/urls.py
accounts/views.py
chat/views.py
dear_bebe_prj/urls.py
requests/models.py

아이디 중복 확인 기능 구현
중복 확인 여부 ui는 아직 구현 전인 것 같아, 터미널에서 print()로 확인하게 구현했습니다

feat: 아이디 중복 확인 기능 구현

---

accounts/static/accounts/common.css
accounts/static/accounts/js/location.js
accounts/static/accounts/location.css
accounts/static/accounts/login.css
accounts/static/accounts/signup.css
accounts/templates/accounts/location.html
accounts/templates/accounts/signup.html

로그인/회원가입/지역인증 페이지의 css 수정
- 페이지 내 컴포넌트 width 90%로 맞춤
- 지역 인증 페이지 '동네 인증 완료' 버튼 클릭 시 색 변경(버그 수정)

fix: 로그인/회원가입/지역인증 페이지 css 수정

---

accounts/models.py
accounts/templates/accounts/login.html
accounts/templates/accounts/signup.html
accounts/urls.py
accounts/views.py
dear_bebe_prj/settings.py

feat: 로그인 기능 구현

---

chat/forms.py
chat/models.py
chat/urls.py
chat/views.py
dear_bebe_prj/settings.py
dear_bebe_prj/urls.py

- 쪽지방 자동 생성
- 쪽지방 목록 조회
- 쪽지방 상세 채팅 화면
- 메시지 전송
- 거래 완료 처리

feat: 쪽지방 생성, 목록 조회, 채팅 화면, 메시지 전송, 거래 완료 처리 구현 

---

accounts/static/accounts/js/login.js
accounts/static/accounts/js/signup.js
accounts/static/accounts/login.css
accounts/static/accounts/signup.css
accounts/templates/accounts/login.html
accounts/templates/accounts/signup.html
accounts/views.py

- 아이디 중복 확인 출력 UI 구현
- 로그인 페이지 확인 UI 구현
- 로그인 로딩시간 고려해 스플래시 스크린 한 번만 뜨게 수정
구현 과정에서 views.py 메세지 부분 일부 수정이 있었습니다. 테스트 결과 작동에 이상은 없는 걸 확인했습니다.

feat: 아이디 중복 확인, 로그인 확인 UI 구현

---

reviews/urls.py
reviews/views.py

- 작성한 후기/받은후기/별점평균 렌더링
- 본인이 작성한 후기 삭제 기능

feat: 후기 목록 조회

---

reviews/static/reviews/change.css
reviews/static/reviews/js/review-post.js
reviews/static/reviews/myreview.css
reviews/static/reviews/review_post.css
reviews/static/reviews/share.css
reviews/templates/reviews/change.html
reviews/templates/reviews/myreview.html
reviews/templates/reviews/review_post.html
reviews/templates/reviews/share.html

- 후기 작성 페이지 사진 첨부 시 미리보기 기능 구현
(직전 PR로 보낸 게시글 작성 페이지 사진 미리보기 기능과 동일)
- 교환/나눔 내역, 나의 후기 페이지 nav바 css 수정

feat: 후기 작성 페이지 사진 미리보기 구현 / nav바 수정

---

posts/static/posts/detail.css
posts/templates/posts/detail.html
posts/templates/posts/exchange.html
posts/templates/posts/free.html
requests/static/requests/received_list.css

- 게시글 상세, 교환/나눔 신청 페이지에 load static 태그 추가
- 미세한 css 수정

fix: 템플릿 태그, css 등 수정

---

accounts/static/accounts/js/location.js
accounts/templates/accounts/location.html

회원가입 - 동네 설정 페이지 지역 인증 기능 구현
- Geolocation API, 카카오맵 API 활용(API 키 필요)
- 일단 현재 위치 기반(GPS 허용해야 가능)기능만 구현. 추후 지역 검색도 (시간이 나면) 구현 예정.
테스트 시에는 카카오 API 키가 필요합니다. 프론트엔드 JS 환경에서 API 키 숨기기가 애매해보여서 일단 API 키만 빼고 PR 보내니, 테스트 필요하신 경우엔 말씀해주시면 개인 톡으로 보내드리겠습니다. location.js 파일의 KAKAO_REST_API_KEY 쌍따옴표 안에 복붙하시면 됩니다!

feat: 지역 인증 기능 구현

---

home/templates/home/home_main.html
home/templates/home/home_search.html
home/views.py

키워드 검색 기능 구현

---

accounts/admin.py
chat/admin.py
requests/admin.py
reviews/admin.py

feat: admin에 앱 등록

---

posts/static/posts/js/update.js
posts/static/posts/post.css
posts/templates/posts/detail.html
posts/templates/posts/update.html
posts/urls.py
posts/views.py

게시글 수정 기능 구현
- views.py에 post_update() 함수 추가
- urls.py에 /update 링크 추가
- modify.html, modify.js -> update.html, update.js 이름 변경
- update.html에 기존에 올라간 사진 및 항목도 불러오도록 템플릿 태그 추가
- update.js : 기존에 올라간 사진 포함 3장 이상 못 올리도록 기능 구현
기존페이지
게시글 수정 페이지
수정 결과
원래는 게시글 수정 페이지 사진 미리보기 기능만 수정하려고 헀으나, 제가 보면서 고치려면 그냥 연동해서 구현까지 가는 게 나을 것 같아서 그런 식으로 처리했습니다. 작동 이상 있을 경우 편하게 수정해주세요! 추후 작성/수정 페이지에서 이미지 삭제 기능도 구현할 수는 있을 것 같습니다.

feat: 게시글 수정 기능 구현

---

accounts/views.py
posts/templates/posts/detail.html
posts/templates/posts/exchange.html
posts/templates/posts/free.html
posts/urls.py
posts/views.py

나눔 신청 구현 완료,
나눔 신청을 클릭하고 모달 창이 뜨지 않는 오류 수정,
작성자일 경우 나눔, 교환 여부에 따라 받은 신청 관리로 이동
작성자 x, 해당 게시글에 대해 이미 신청한 적 있는 사람일 경우 나눔, 교환 여부에 따라 보낸 신청 관리로 이동하는 로직 추가, 그에 맞는 버튼 ui도 수정하였습니다.

feat: 나눔 신청 구현, 모달 창 오류 수정, 버튼 수정

---

chat/urls.py
chat/views.py
posts/admin.py
requests/models.py
requests/templates/requests/received_donation_list.html
requests/templates/requests/received_exchange_list.html
requests/templates/requests/sent_donation_list.html
requests/templates/requests/sent_exchange_list.html
requests/views.py
reviews/templates/reviews/review_post.html

- 내가 올린 나눔글에 받은 신청 조회 성공
- 쪽지하기 버튼 클릭 시 채팅방으로 이동
추후 수정할 사항
- 거절하기 버튼 css가 안 먹음
- 날짜 표시 7/8 식으로 변환
- 거절 기능 수정
- 채팅 기능 수정

feat: 나눔-받은 신청 조회 연동

---

chat/static/chat/js/chat.js
chat/templates/chat/chat.html
chat/templates/chat/chat_list.html
chat/views.py
requests/views.py

- 쪽지하기 클릭시 쪽지방 생성 연동
- 쪽지 기능 연동
- 쪽지 목록 조회 연동 
- 쪽지에서 빈값 전송 안 되게 처리해야함
- 쪽지에서 이미지 첨부시 미리보기 구현해야함
- 거래완료 클릭시 db에서 상태 변하는 것까지 확인함 (ui 수정 필요)

feat: 쪽지, 쪽지 목록 조회

---

requests/templates/requests/received_exchange_list.html
requests/views.py

- 교환-받은신청 목록 조회, 거절 연동
- 쪽지하기 css가 반영 안 됨

feat: 교환-받은신청 목록 조회, 거절 연동

---

chat/views.py
requests/templates/requests/sent_exchange_list.html

- 채팅방 생성된 후 메세지 하나라도 보낼 시 신청 관리에서 대기중으로 바뀌게 수정
- 이미지는 db에 안 넣음
- 중간에 현재 상태는 확인차 찍은 것 (삭제함)

fix: 채팅 시작 후 status 변환 기능 수정

---

chat/models.py
chat/static/chat/chat_list.css
chat/templates/chat/chat.html
chat/templates/chat/chat_list.html
chat/views.py
posts/templates/posts/detail.html
requests/templates/requests/received_donation_list.html
requests/templates/requests/received_exchange_list.html
requests/templates/requests/sent_donation_list.html
requests/templates/requests/sent_exchange_list.html
reviews/static/reviews/mypage.css
reviews/templates/reviews/edit.html
reviews/templates/reviews/mypage.html
reviews/views.py

- 프로필 사진 변경 기능 수정(구현 완료)
- 쪽지 목록, 쪽지방 상대방 프로필 사진 적용
(이 과정에서 models.py, views.py 수정이 있었습니다...!)
- 게시글 상세 페이지 작성자 프로필 사진 적용
- 신청 관리 목록 프로필 사진 적용
(받은 신청 : 신청 보낸 사람 프로필 / 보낸 신청 : 최초 게시글 작성자 프로필)
나의 후기 부분은 연동이 진행중인 것 같아 일단은 그냥 두었습니다. 오류가 난다면 언제든 말씀해주세요!

feat: 프로필 사진 변경 기능 수정, 프로필 사진 연동

---

reviews/templates/reviews/edit.html

fix: 뒤로 가기 버튼 추가

---

home/static/home/home_search.css
home/templates/home/home_main.html
home/templates/home/home_search.html
home/templates/home/profile.html

프로필 넘어가는 url 부분 확인 부탁드립니다!
search, main 홈 부분에 plus 버튼 추가했습니다.
프로필 화면에도 리뷰사진 추가했습니다.

feat: 프로필 페이지 충돌 해결 및 plus 버튼 추가

---

accounts/static/accounts/js/signup.js
accounts/templates/accounts/signup.html
reviews/static/reviews/js/edit.js
reviews/templates/reviews/edit.html

- 회원가입, 프로필 수정 시 아이디 중복확인을 꼭 눌러야 하도록 로직 수정.
(최종 제출 시 중복확인을 누르지 않은 경우 중복확인 해달라는 alert 띄움)
- 회원가입, 프로필 수정 시 아이디 조건에 맞지 않으면 중복확인 불가능하도록 수정.
(이 부분은 alert가 뜨진 않습니다. 어차피 아이디 관련 경고멘트가 있어서 괜찮을 것 같아요.)
오류가 있다면 언제든 말씀해주세요!

fix: 회원가입, 프로필 수정 중복확인 로직 수정

---

chat/static/chat/chat.css
chat/static/chat/js/chat.js
chat/templates/chat/chat.html

- 거래 완료 모달 추가
- 기존 거래 완료 확인 모달 로직 변경
: 이제 기존 모달이 아닌 새로 추가된 '거래가 완료되었습니다!' 모달의 확인을 눌러야 거래완료가 전송됩니다.
오류가 있다면 말씀해주세요!

feat: 거래 완료 모달 추가

---

chat/templates/chat/chat.html
chat/views.py
reviews/templates/reviews/mypage.html
reviews/templates/reviews/share.html
reviews/urls.py
reviews/views.py

- 나눔 받은 내역 조회 연동
- 쪽지 상단에 거래 상태 연동 수정해야함

feat: 마이페이지-나눔 받은 내역 조회 연동

---

reviews/static/reviews/js/edit.js
reviews/templates/reviews/edit.html

프로필 수정 페이지 내에서, 다음 경우엔 아이디 중복확인을 하지 않아도 되게 수정했습니다.
- 닉네임이나 프로필 사진만 바꿨을 때 (아이디 input 자체를 건드리지 않았을 때)
- 중복확인 이력이 있더라도, 최종적으로 아이디 input의 값이 현재 아이디와 동일할 때
오류가 있다면 말씀해 주세요!

fix: 프로필 수정 중복확인 로직 수정

---

accounts/static/accounts/js/signup.js
home/templates/home/home_main.html
home/templates/home/home_search.html

회원이 저장되지 않는 오류가 있어 해당 부분 js수정,
홈 플러스 버튼과 post-add 연결
상대방 프로필 후기 사진 연동
문제 있는 부분은 모두 연락 드렸습니다!

fixfix: 회원가입 로직 수정, 홈 플러스 버튼 연결, 상대방 프로필 후기 사진 연결

---

home/static/home/home_main.css
home/static/home/profile.css
home/templates/home/home_main.html
home/templates/home/home_nopost.html
home/templates/home/home_search.html
home/templates/home/profile.html

홈화면 하단 플러스 버튼 누를 시 글쓰기 페이지로 이동

feat: 홈화면 플러스버튼 페이지 이동

---

home/static/home/home_main.css
home/static/home/home_search.css

홈 화면 css 수정
push 전에 충돌 해결 잘 부탁드립니다...!

fix: 홈 화면 css 수정

---

reviews/templates/reviews/mypage.html
reviews/templates/reviews/myreview.html
reviews/urls.py
reviews/views.py

- 받은 후기 조회 연동
- 별점 ui 부분 수정해야합니다

feat: 받은 후기 조회 연동

---

reviews/static/reviews/share.css
reviews/templates/reviews/change.html
reviews/templates/reviews/sent-share.html
reviews/templates/reviews/share.html
reviews/views.py

feat: 교환, 나눔 내역 연동 > 후기 작성하기 페이지 이동
css 깨짐, html 구조 문제가 있습니다..

feat: 교환, 나눔 내역 연동

---

reviews/static/reviews/change.css
reviews/static/reviews/share.css
reviews/templates/reviews/change.html
reviews/templates/reviews/sent-share.html
reviews/templates/reviews/share.html

- 교환/나눔 내역 HTML 구조 문제 해결 (CSS 문제도 자연스럽게 해결됐어요)
- 교환/나눔 내역 헤더 수정 (다른 페이지와 일관성을 줬습니다. 다른 페이지도 시간 날 때 헤더 수정 진행할 예정입니다.)
PR이 연달아 가면서 pull 할 때 충돌이 발생할 수도 있을 것 같습니다...! 수정사항 생기면 바로 수정하겠습니다!

fix: 교환/나눔 내역 css 문제 해결

---

reviews/static/reviews/js/myreview.js
reviews/static/reviews/mypage.css
reviews/static/reviews/myreview.css
reviews/templates/reviews/mypage.html
reviews/templates/reviews/myreview.html
reviews/urls.py
reviews/views.py

- 나의 후기 페이지에 별점이 제대로 연동되지 않던 오류를 수정했습니다.
- 나의 후기 작성된 후기 지우는 로직 오류를 수정했습니다. (모달에서 확인 눌러야 지워지는 방식)
- 나의 후기 페이지와 마이페이지의 헤더 css를 변경했습니다. (다른 페이지와 일관성을 줬습니다.)
urls.py와 views.py에 수정이 있었습니다. 오류가 발생한다면 언제든 말씀해주세요!

fix: 나의 후기 페이지 연동 오류 수정, 마이페이지 헤더 css 변경

---

chat/static/chat/chat_list.css
posts/static/posts/detail.css
posts/static/posts/post.css
reviews/static/reviews/edit.css
reviews/static/reviews/review_post.css

쪽지 목록, 게시글 상세, 게시글 작성, 프로필 수정, 후기 작성 등의 페이지에서 헤더 디자인을 통일했습니다.

style: 헤더 css 통일

---

accounts/static/accounts/location.css
accounts/static/accounts/signup.css
chat/static/chat/chat.css
chat/static/chat/chat_list.css
posts/static/posts/detail.css
posts/static/posts/post.css
requests/static/requests/received_list.css
reviews/static/reviews/change.css
reviews/static/reviews/edit.css
reviews/static/reviews/mypage.css
reviews/static/reviews/myreview.css
reviews/static/reviews/review_post.css
reviews/static/reviews/share.css

헤더 글자 크기 22px -> 20px로 변경
(시안에서 20px이었더라고요...머쓱)

style: 헤더 글자 크기 변경

---

chat/static/chat/js/chat.js
chat/templates/chat/chat.html

- 쪽지방 거래 완료 버튼 연동 
https://github.com/user-attachments/assets/e5abbeeb-466a-4569-bdfb-6e384bf68bc6
- 회색 거래 완료 버튼 ui 수정 필요합니다

feat: 쪽지방 거래 완료 버튼 연동

---

reviews/static/reviews/mypage.css
reviews/static/reviews/myreview.css

마이페이지 > 나의 후기 부분 글 작성 줄바꿈 수정,
사진, 날짜 밀리지 않도록 수정했습니다

fix:나의 후기 수정

---

chat/static/chat/chat.css
reviews/static/reviews/js/myreview.js
reviews/static/reviews/js/share.js
reviews/static/reviews/myreview.css
reviews/static/reviews/share.css

- 나눔 내역 드롭다운의 보여지는 로직 일부를 수정했습니다. (누르면 드롭다운 아이콘 안 보이게)
- 나의 후기에서 200자 내외의 긴 글도 대응할 수 있게 일부 수정했습니다.
- 나의 후기 드롭다운의 순서를 현재 페이지에 맞게 수정했습니다.
수정사항 있으면 말씀해주세요!

fix: 나의 후기, 나눔 내역 css 수정

---

chat/views.py
posts/models.py
requests/views.py
reviews/templates/reviews/myreview.html
reviews/templates/reviews/sent-share.html
reviews/templates/reviews/share.html

- 작성자가 올린 나눔/교환 용품 거래 완료시, 해당 용품에 받은 다른 신청들 삭제 처리
- item 모델에 status 필드 추가
- 풀 하고 마이그레이션 부탁드립니다 :)

feat: 거래 완료 시 받은 신청 처리 (풀하고 마이그레이션 필요)

---

accounts/views.py
requests/models.py
reviews/templates/reviews/change.html
reviews/templates/reviews/share.html
reviews/views.py

fix: 작성한 후기 삭제 후 재작성 못하게 수정

---

chat/templates/chat/chat.html
reviews/static/reviews/js/mypage.js
reviews/static/reviews/mypage.css
reviews/templates/reviews/mypage.html

로그아웃 모달창 + 모달창 닫히는 로직 완성했습니다.
action 부분에 뷰만 넣어주시면 될 것 같아요.

feat: 로그아웃 모달창 css 완성

---

chat/models.py
chat/views.py

- 기존 코드가 세션 기반이라 로그인할 때마다 초기화되어 쪽지 목록의 모든 방에 빨간 알림이 뜸 -> ThreadReadStatus 모델 추가하여 마지막 읽음 시간 저장하여 해결

fix: 쪽지 빨간 알림 수정

---

accounts/urls.py
accounts/views.py
reviews/static/reviews/js/mypage.js
reviews/templates/reviews/mypage.html

feat: 로그아웃 연동

---

home/static/home/profile.css
home/templates/home/profile.html

상대방 프로필 페이지 css 수정
(스크롤 안 보이게 함, 각종 오류 수정 등)
각 div 내의 스크롤만 가능하도록 어느 정도 고정시켜둔 구조입니다.

fix: 상대방 프로필 페이지 css 수정

---

home/static/home/home_main.css
home/static/home/home_nopost.css
home/static/home/home_search.css

홈 화면 헤더 부분을 좀 더 시안에 가깝게 수정했습니다.
혹시 깨진다면 말씀해주세요!

fix: 홈 화면 헤더 css 수정
